Repository TableLog/tablelog-back, pull requests merged in 2025-06, with the labels that each got.

#117 Feature/shopping list/crud - ShoppingList CRUD 기능 구현 및 레시피 조회 관련 수정
  src/main/java/com/tablelog/tablelogback/domain/recipe/controller/RecipeController.java
  src/main/java/com/tablelog/tablelogback/domain/recipe/dto/service/RecipeFoodPreviewDto.java
  src/main/java/com/tablelog/tablelogback/domain/recipe/dto/service/RecipeFoodPreviewSliceResponseDto.java
  src/main/java/com/tablelog/tablelogback/domain/recipe/exception/RecipeErrorCode.java
  src/main/java/com/tablelog/tablelogback/domain/recipe/service/RecipeService.java
  src/main/java/com/tablelog/tablelogback/domain/recipe/service/impl/RecipeServiceImpl.java
  src/main/java/com/tablelog/tablelogback/domain/recipe_food/repository/RecipeFoodRepository.java
  src/main/java/com/tablelog/tablelogback/domain/recipe_food/service/impl/RecipeFoodServiceImpl.java
  src/main/java/com/tablelog/tablelogback/domain/recipe_process/controller/RecipeProcessController.java
  src/main/java/com/tablelog/tablelogback/domain/recipe_process/dto/service/RecipeProcessSliceResponseDto.java
  src/main/java/com/tablelog/tablelogback/domain/recipe_process/entity/RecipeProcess.java
  src/main/java/com/tablelog/tablelogback/domain/recipe_process/repository/RecipeProcessRepository.java
  src/main/java/com/tablelog/tablelogback/domain/recipe_process/service/RecipeProcessService.java
  src/main/java/com/tablelog/tablelogback/domain/recipe_process/service/impl/RecipeProcessServiceImpl.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/controller/ShoppingListController.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/dto/controller/ShoppingListCreateControllerRequestDto.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/dto/controller/ShoppingListUpdateControllerRequestDto.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/dto/service/ShoppingListCreateServiceRequestDto.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/dto/service/ShoppingListReadAllServiceResponseDto.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/dto/service/ShoppingListSliceResponseDto.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/dto/service/ShoppingListUpdateServiceRequestDto.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/entity/ShoppingList.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/exception/ForbiddenAccessShoppingListException.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/exception/NotFoundShoppingListException.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/exception/ShoppingListErrorCode.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/mapper/dto/ShoppingListDtoMapper.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/mapper/entity/ShoppingListEntityMapper.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/repository/ShoppingListRepository.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/service/ShoppingListService.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/service/impl/ShoppingListServiceImpl.java
Labels: Refactor, feature

#123 Refactor/Shopping-list/Create-res - ShoppingList 생성 시 response 로 id 값 반환하도록 수정
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/controller/ShoppingListController.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/service/ShoppingListService.java
  src/main/java/com/tablelog/tablelogback/domain/shopping_list/service/impl/ShoppingListServiceImpl.java
Labels: Refactor

#125 Refacotr/redisconfig
  Dockerfile
  build.gradle
  src/main/java/com/tablelog/tablelogback/domain/chat/controller/ChatController.java
  src/main/java/com/tablelog/tablelogback/domain/chat/service/Impl/ChatServiceImpl.java
  src/main/java/com/tablelog/tablelogback/global/config/RedisConfig.java
  src/main/java/com/tablelog/tablelogback/global/config/WebSecurityConfig.java
  src/main/java/com/tablelog/tablelogback/global/jwt/RefreshToken.java
Labels: Refactor(수정)
